import React,{useEffect} from "react";
import Head from 'next/head'
import {Flex, Box, Container,SimpleGrid, Grid, GridItem,Divider,Text, AspectRatio, Button, Image, VStack, Stack, HStack, Link, Heading} from '@chakra-ui/react';
import { Card, CardHeader , CardBody, CardFooter } from '@chakra-ui/card'
import {ButtonGroup} from '@chakra-ui/button'
import Testimonials from '../components/Testimonials'
import anime from "animejs"
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';

export default function Home() {
  const wave1 = "M0 108.306L50 114.323C100 120.34 200 132.374 300 168.476C400 204.578 500 264.749 600 246.698C700 228.647 800 132.374 900 108.306C1000 84.2382 1100 132.374 1150 156.442L1200 180.51V0H1150C1100 0 1000 0 900 0C800 0 700 0 600 0C500 0 400 0 300 0C200 0 100 0 50 0H0V108.306Z"
		const wave2 = "M0 250L50 244.048C100 238.095 200 226.19 300 226.19C400 226.19 500 238.095 600 232.143C700 226.19 800 202.381 900 196.429C1000 190.476 1100 202.381 1150 208.333L1200 214.286V0H1150C1100 0 1000 0 900 0C800 0 700 0 600 0C500 0 400 0 300 0C200 0 100 0 50 0H0V250Z"
		const wave3 = "M0 250L50 238.095C100 226.19 200 202.381 300 166.667C400 130.952 500 83.3333 600 101.19C700 119.048 800 202.381 900 214.286C1000 226.19 1100 166.667 1150 136.905L1200 107.143V0H1150C1100 0 1000 0 900 0C800 0 700 0 600 0C500 0 400 0 300 0C200 0 100 0 50 0H0V250Z"
		const wave4 = "M0 125L50 111.111C100 97.2222 200 69.4444 300 97.2222C400 125 500 208.333 600 236.111C700 263.889 800 236.111 900 229.167C1000 222.222 1100 236.111 1150 243.056L1200 250V0H1150C1100 0 1000 0 900 0C800 0 700 0 600 0C500 0 400 0 300 0C200 0 100 0 50 0H0V125Z"
		useEffect(() =>{
		anime({
		targets: '.wave-top > path',
		easing: 'linear',
		duration: 3000,
		loop: true,
		d: [
			{ value: [wave1, wave2] },
			{ value: wave3 },
			{ value: wave4 },
			{ value: wave1 },
		],
		});
	},[]);

  return (
    <Box>
      <Head>
        <title>Aubreys Curation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex  bgColor="#FEDADA" as="main" role="main" direction={{ sm: 'column', md: 'row', lg: 'row'  }} >
       
            {/* HERO TITLE */}
            <Flex  p={20} direction={{ sm: 'column', md: 'row', lg: 'row'  }} bgColor="#FEDADA" display="flex" >
              <Box >
                <Heading  as='h1' fontSize={{sm:50,md:60,lg:100}} textShadow="black 1px 1px 1px" color="#C2176C">Be the best version of yourself</Heading>
                <Text   w="70%" color="gray.600" fontSize={{sm:16,md:18,lg:20}} mt={5}>We are committed to providing the highest quality and certified skin care products and customer service.</Text>
                {/* Social Media Links */}
                  <HStack  mt={10}>
                    <Link><Image src="images/Facebook.png" alt="Facebook" boxSize={50} /></Link>
                    <Link><Image src="images/Instagram.png" alt="instagram logo" boxSize={50}/></Link>
                    <Link><Image src="images/Shopee.png" alt="shoppe" boxSize={50}/></Link>
                    <Link><Image src="images/Tiktok.png" alt="tiktok logo" boxSize={50}/></Link>
                    <Link><Image src="images/Youtube.png" alt="youtube logo" boxSize={50}/></Link>
                  </HStack>
                <Button rightIcon={<ShoppingCartIcon/>} data-aos="zoom-out" _hover={{
                      background: "white",
                      color: "teal.500",
                    }} mt={10} p={6} boxShadow="black 1px 1px 1px" color="white" background="#FF5975">Shop Now</Button>
                </Box>
              <Box >
                <Image display={{sm:'none', md:'flex', lg: 'flex'}} src="images/Hero.png" w={{sm:400, md:500, lg:600}} w={{sm:400, md:500, lg:600}}/>
              </Box>
            </Flex>
  
      </Flex>  
      
      <Flex justify="center">
      <Image data-aos="fade-up"  src="/images/vector.png"  justify="center" w="50%" />
              <Box mt={20} pos={{lg:"absolute"}} ><iframe
                pos="absolute"
                title='Aubreys'
                src='/videos/video.mp4'
                loading="ease"
                loop="true"
                allowFullScreen width="520" height="390" 
              /> </Box>

   
      </Flex>
     
      <Flex h="full"  direction="column" background="#FF5975" justify="center">
      <Flex>
        <svg className="wave-top" width="100vw" viewBox="0 50 1000 250"> 
  				  <path fillRule="evenodd" clipRule="evenodd" d="M0 108.306L50 114.323C100 120.34 200 132.374 300 168.476C400 204.578 500 264.749 600 246.698C700 228.647 800 132.374 900 108.306C1000 84.2382 1100 132.374 1150 156.442L1200 180.51V-8.5451e-06H1150C1100 -8.5451e-06 1000 -8.5451e-06 900 -8.5451e-06C800 -8.5451e-06 700 -8.5451e-06 600 -8.5451e-06C500 -8.5451e-06 400 -8.5451e-06 300 -8.5451e-06C200 -8.5451e-06 100 -8.5451e-06 50 -8.5451e-06H0V108.306Z" fill="#FEDADA"/>
		   	</svg>
      </Flex> 
        <Heading aos-data="fade-down" p={10} color="white" textAlign="center" fontSize={{sm:"35",md:40,lg:60}}>Featured Products</Heading>
        <Flex direction="column" justify="center">
        <SimpleGrid p={10} columns={[1, null, 4]} spacing="40px">
            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='pink.200' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product2.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='red.500' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product3.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='red.500' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product4.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='red.500' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product5.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='red.500' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product6.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='red.500' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product7.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='red.500' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            <Card data-aos="zoom-in" background="white" p={10} boxShadow='lg'borderRadius="lg" maxW="sm">
                  <CardBody p={2}>  
                        <Image src="/images/product8.JPG" borderRadius="lg" alt="rosmar-soap-1" w="300px"/>
                        <Stack mt='6' spacing='3'>
                          <Text color='pink.600' fontStyle="bold" fontSize='2xl'>Rosmar Kagayaku Soap</Text>
                          <Text fontSize="sm">
                              This soap is perfect for every skin.
                            </Text>
                            <Text color='pink.200' fontSize='2xl'>
                              $450
                            </Text>
                        </Stack>
                  </CardBody> 
                  <Divider />
                  <CardFooter>
                    <ButtonGroup mt={3} spacing='2'>
                      <Button variant='solid' colorScheme='pink'>
                        Buy now
                      </Button>
                    </ButtonGroup>
                  </CardFooter>
            </Card>

            
        </SimpleGrid>
        <Flex justify="center">
          <Button p={6} size="2xl"><Link href="/products">More Products</Link></Button>        
           
        </Flex>  
      </Flex>

      </Flex>
      <Flex>
        <svg className="wave-top" width="100vw" viewBox="0 50 1000 250"> 
  				  <path fillRule="evenodd" clipRule="evenodd" d="M0 108.306L50 114.323C100 120.34 200 132.374 300 168.476C400 204.578 500 264.749 600 246.698C700 228.647 800 132.374 900 108.306C1000 84.2382 1100 132.374 1150 156.442L1200 180.51V-8.5451e-06H1150C1100 -8.5451e-06 1000 -8.5451e-06 900 -8.5451e-06C800 -8.5451e-06 700 -8.5451e-06 600 -8.5451e-06C500 -8.5451e-06 400 -8.5451e-06 300 -8.5451e-06C200 -8.5451e-06 100 -8.5451e-06 50 -8.5451e-06H0V108.306Z" fill="#FF5975"/>
		   	</svg>
      </Flex> 
      <Flex p={10} display="flex" direction="column" h="full" align="center" justify="center" >
        <Heading fontSize={{sm:35, md:45, lg:70}}aos-data="fade-up" p={20} justify="center" align="center" color="gray.700">Our Trusted Partners</Heading>
        <SimpleGrid alignItems="center"  columns={[1, null, 5]} spacing="20px">
              <Image data-aos="zoom-in" src="/images/rosmar.png" alt="rosmar-logo"  height="60"/>
              <Image data-aos="zoom-in" src="/images/psph.png" alt="rosmar-logo"  height="50"/>
              <Image data-aos="zoom-in" src="/images/gluta.png" alt="rosmar-logo" height="100"/>
              <Image data-aos="zoom-in" src="/images/brilliant.png" alt="rosmar-logo"  height="50"/>
              <Image data-aos="zoom-in" src="/images/fairy.png" alt="rosmar-logo"  height="200"/>
          
        </SimpleGrid>
      </Flex>
      <Flex p={10} mt={10} display="flex" direction={{sm:"column", md:"column",lg:"row"}} align="center" justify="space-around" >
                  <Image src="/images/delivery.png" alt="delivery truck"></Image>
                  <Stack maxW='md' >
                    <Heading color="#BC2973">Delivery is safe and secure</Heading>
                    <Text>A bundle of 210+ ready-to-use, responsive and accessible components with clever structured sourcode files</Text>
                    <Button size='2xl'>Order Now</Button>
                  </Stack>
      </Flex>
      <Flex p={10} display="flex" direction="column" align="center" justify="center">
        <Box p={2} justify="center" align="center">
          <Image src="/images/Pretty Woman.png" alt="woman"/>
          <Heading color="#BC2973">Why Aubrey Curations?</Heading>
          <Text>Because this beautiful and responsive React components will help your to realize your next project in no time.</Text>
        </Box> 
          <Grid justify="space-between" align="center"
          templateColumns={{
          base: 'repeat(1, 1fr)',
          sm: 'repeat(2, 1fr)',
          md: 'repeat(4, 1fr)',
            }}
            gap={6}>
              <GridItem data-aos="fade-right" justify="center"w="100%" colSpan={{ base: 1, sm: 2, md: 2 }}>
                 <Image src="/images/map.png" alt=""/>
              </GridItem>
              <Grid data-aos="fade-left" p={20} justify="center" templateColumns={{
          base: 'repeat(2, 1fr)',
          sm: 'repeat(2, 1fr)',
          md: 'repeat(2, 1fr)',
            }} gap={10}>
              <GridItem p={5} w="100%">
                <Flex flexDirection={'column'}>
                  <Text fontSize={'4xl'} fontWeight={'bold'}>
                    200+
                  </Text>
                  <Box fontSize={'sm'}>
                    Affiliated Resellers
                  </Box>
                  </Flex>
                </GridItem>
                <GridItem p={5} w="100%">
                  <Flex flexDirection={'column'}>
                    <Text fontSize={'4xl'} fontWeight={'bold'}>
                      150
                    </Text>
                    <Box fontSize={'sm'}>
                      Cities Distributed
                    </Box>
                  </Flex>
                </GridItem>
                <GridItem p={5} w="100%">
                  <Flex flexDirection={'column'}>
                    <Text fontSize={'4xl'} fontWeight={'bold'}>
                      150
                    </Text>
                    <Box fontSize={'sm'}>
                      Cities Distributed
                    </Box>
                  </Flex>
                </GridItem>
                <GridItem p={5}  w="100%">
                  <Flex flexDirection={'column'}>
                    <Text fontSize={'4xl'} fontWeight={'bold'}>
                      1M
                    </Text>
                    <Box fontSize={'sm'}>
                      Orders Delivered
                    </Box>
                  </Flex>
                </GridItem>
              </Grid>    
        </Grid>   
      </Flex>
      <Flex data-aos="fade-down" p={10} display="flex" direction="column" justify="flex-start">
        <Testimonials/>
      </Flex>
     
    </Box>
  )
}
